/**
 * DEMO SEED DATA — Synthetic / illustrative data only.
 * All events are fictional and are NOT verified real-world facts.
 * Intended for UI demonstration and development purposes.
 */
import { pool } from "./client";
import "dotenv/config";

interface SeedEvent {
  title: string;
  summary: string;
  description?: string;
  event_type: string;
  severity: number;
  confidence_score: number;
  verification_status: string;
  geolocation_precision: string;
  latitude: number;
  longitude: number;
  location_radius_km?: number;
  country: string;
  region?: string;
  city?: string;
  hours_ago: number;
  sources: Array<{
    name: string;
    source_type: string;
    url?: string;
    publisher?: string;
    reliability_score: number;
    raw_text?: string;
  }>;
}

const seedEvents: SeedEvent[] = [
  // Iran - Tehran area
  {
    title: "[DEMO] Explosion reported near industrial district, Tehran",
    summary: "Multiple witnesses report a large explosion near an industrial complex north of Tehran. Emergency services dispatched.",
    description: "Social media reports and local news outlets describe a loud blast heard across several districts. Smoke visible from multiple vantage points. Cause under investigation.",
    event_type: "explosion",
    severity: 3,
    confidence_score: 62,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 35.7448,
    longitude: 51.3890,
    location_radius_km: 5,
    country: "Iran",
    region: "Tehran Province",
    city: "Tehran",
    hours_ago: 2,
    sources: [
      { name: "Local News Wire", source_type: "news", publisher: "Tehran Today", reliability_score: 60, raw_text: "Massive explosion heard in northern Tehran industrial zone" },
      { name: "Social Report #1", source_type: "social", reliability_score: 35, raw_text: "Huge blast near the factory area, smoke visible from my rooftop" },
    ],
  },
  {
    title: "[DEMO] Drone activity detected over Tehran outskirts",
    summary: "Multiple unidentified drone objects tracked over eastern Tehran suburbs. Air defense systems activated.",
    event_type: "drone",
    severity: 4,
    confidence_score: 78,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 35.7200,
    longitude: 51.5500,
    location_radius_km: 8,
    country: "Iran",
    region: "Tehran Province",
    city: "Tehran",
    hours_ago: 5,
    sources: [
      { name: "Aviation Monitor Feed", source_type: "api", publisher: "FlightWatch", reliability_score: 75, raw_text: "Unidentified aerial objects detected east of Tehran, altitude low" },
      { name: "Witness Account", source_type: "social", reliability_score: 40, raw_text: "Saw strange flying objects, then heard sirens" },
    ],
  },
  // Natanz
  {
    title: "[DEMO] Strike reported near Natanz enrichment facility",
    summary: "Reports of an airstrike or explosion near the Natanz nuclear site. Coordinates approximate due to restricted area.",
    description: "Satellite thermal anomaly detected 2.3km from the facility perimeter. Corroborated by two news sources citing local witnesses.",
    event_type: "airstrike",
    severity: 5,
    confidence_score: 71,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 33.5214,
    longitude: 51.9201,
    location_radius_km: 10,
    country: "Iran",
    region: "Isfahan Province",
    city: "Natanz",
    hours_ago: 14,
    sources: [
      { name: "Satellite Thermal Sensor", source_type: "satellite", reliability_score: 80, raw_text: "Thermal anomaly detected near Natanz coordinates" },
      { name: "Regional News", source_type: "news", publisher: "IRNA Monitor", reliability_score: 55, raw_text: "Loud sounds reported near enrichment facilities" },
    ],
  },
  // Isfahan
  {
    title: "[DEMO] Air defense activity, Isfahan",
    summary: "Interceptor missiles fired from Isfahan air defense batteries. Target unclear.",
    event_type: "missile",
    severity: 4,
    confidence_score: 85,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 32.6539,
    longitude: 51.6660,
    location_radius_km: 15,
    country: "Iran",
    region: "Isfahan Province",
    city: "Isfahan",
    hours_ago: 8,
    sources: [
      { name: "Defense Monitor", source_type: "news", publisher: "WarZone Report", reliability_score: 80, raw_text: "Air defense interceptors seen launching over Isfahan" },
      { name: "Thermal Scan A7", source_type: "satellite", reliability_score: 82, raw_text: "Multiple heat signatures consistent with missile launches" },
      { name: "Open Source Analyst", source_type: "manual", reliability_score: 85, raw_text: "Video verified, missile trails visible in footage" },
    ],
  },
  // Bushehr
  {
    title: "[DEMO] Security alert near Bushehr nuclear plant",
    summary: "Unverified reports of aircraft activity near Bushehr. Plant authorities deny incident.",
    event_type: "alert",
    severity: 3,
    confidence_score: 38,
    verification_status: "unverified",
    geolocation_precision: "area",
    latitude: 28.9684,
    longitude: 50.8385,
    location_radius_km: 25,
    country: "Iran",
    region: "Bushehr Province",
    city: "Bushehr",
    hours_ago: 30,
    sources: [
      { name: "Anonymous Tip", source_type: "social", reliability_score: 20, raw_text: "Something happening near the nuclear plant" },
    ],
  },
  // Shiraz
  {
    title: "[DEMO] Military convoy movement, Shiraz highway",
    summary: "Large armored convoy observed on the Shiraz-Isfahan highway heading north.",
    event_type: "troop_movement",
    severity: 2,
    confidence_score: 72,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 29.5918,
    longitude: 52.5836,
    country: "Iran",
    region: "Fars Province",
    city: "Shiraz",
    hours_ago: 18,
    sources: [
      { name: "Commercial Satellite", source_type: "satellite", reliability_score: 78, raw_text: "High-resolution imagery shows armored vehicles on highway" },
      { name: "Traveler Report", source_type: "social", reliability_score: 30, raw_text: "Long convoy of military trucks blocking lane 2 on highway" },
    ],
  },
  // Tabriz
  {
    title: "[DEMO] Explosion heard in Tabriz, no official confirmation",
    summary: "Residents report hearing a powerful explosion in the Tabriz area. No injuries reported yet.",
    event_type: "explosion",
    severity: 2,
    confidence_score: 42,
    verification_status: "unverified",
    geolocation_precision: "area",
    latitude: 38.0962,
    longitude: 46.2738,
    location_radius_km: 12,
    country: "Iran",
    region: "East Azerbaijan Province",
    city: "Tabriz",
    hours_ago: 46,
    sources: [
      { name: "User Post X", source_type: "social", reliability_score: 25, raw_text: "Big boom heard in Tabriz, anyone else?" },
      { name: "Local Source", source_type: "news", publisher: "Azeri Daily", reliability_score: 50, raw_text: "Unconfirmed reports of explosion in residential district" },
    ],
  },
  // Ahvaz / Khuzestan
  {
    title: "[DEMO] Refinery fire, Ahvaz industrial zone",
    summary: "Fire at an oil refinery facility in Khuzestan Province. Likely industrial accident, not confirmed as attack.",
    event_type: "fire",
    severity: 3,
    confidence_score: 88,
    verification_status: "verified",
    geolocation_precision: "exact",
    latitude: 31.3183,
    longitude: 48.6706,
    country: "Iran",
    region: "Khuzestan Province",
    city: "Ahvaz",
    hours_ago: 72,
    sources: [
      { name: "Oil Industry Monitor", source_type: "news", publisher: "Energy Report ME", reliability_score: 85, raw_text: "Fire confirmed at refinery unit 4, firefighters on scene" },
      { name: "Satellite Hotspot S1", source_type: "satellite", reliability_score: 90, raw_text: "VIIRS thermal anomaly detected, intensity high" },
      { name: "Facility Statement", source_type: "api", reliability_score: 90, raw_text: "Official statement: electrical fire contained" },
    ],
  },
  // Bandar Abbas
  {
    title: "[DEMO] Naval activity spike, Strait of Hormuz approaches",
    summary: "Unusual concentration of naval vessels observed near Bandar Abbas and Strait of Hormuz chokepoint.",
    event_type: "troop_movement",
    severity: 3,
    confidence_score: 80,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 27.1832,
    longitude: 56.2666,
    location_radius_km: 20,
    country: "Iran",
    region: "Hormozgan Province",
    city: "Bandar Abbas",
    hours_ago: 36,
    sources: [
      { name: "Maritime Tracking API", source_type: "api", reliability_score: 85, raw_text: "AIS data shows 12 naval vessels clustered near Bandar Abbas" },
      { name: "Defense Analysis", source_type: "manual", reliability_score: 80, raw_text: "IRGC naval vessels repositioning, formation suggests readiness posture" },
    ],
  },
  // Fordow
  {
    title: "[DEMO] Seismic anomaly near Fordow facility",
    summary: "Seismic sensors recorded a small anomaly near the Fordow underground enrichment site. Could be ground movement or subsurface activity.",
    event_type: "alert",
    severity: 2,
    confidence_score: 45,
    verification_status: "unverified",
    geolocation_precision: "approximate",
    latitude: 34.8859,
    longitude: 50.6010,
    location_radius_km: 8,
    country: "Iran",
    region: "Qom Province",
    city: "Fordow",
    hours_ago: 55,
    sources: [
      { name: "EMSC Feed", source_type: "api", reliability_score: 70, raw_text: "M1.8 event detected near Fordow coordinates" },
    ],
  },
  // Syria - Damascus
  {
    title: "[DEMO] Airstrike reported in Damascus suburb",
    summary: "Reports of airstrikes on Mezzeh district, Damascus. Origin of aircraft unclear.",
    event_type: "airstrike",
    severity: 4,
    confidence_score: 76,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 33.4953,
    longitude: 36.2372,
    location_radius_km: 5,
    country: "Syria",
    region: "Damascus Governorate",
    city: "Damascus",
    hours_ago: 9,
    sources: [
      { name: "Syria Monitor", source_type: "news", publisher: "SOHR", reliability_score: 70, raw_text: "At least three strikes in Mezzeh area reported" },
      { name: "Resident Video", source_type: "social", reliability_score: 45, raw_text: "Video shows smoke rising after impact sounds" },
    ],
  },
  {
    title: "[DEMO] Missile intercepted over Damascus",
    summary: "Syrian air defenses activated over Damascus, at least one ballistic missile reportedly intercepted.",
    event_type: "missile",
    severity: 4,
    confidence_score: 82,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 33.5138,
    longitude: 36.2765,
    location_radius_km: 10,
    country: "Syria",
    region: "Damascus Governorate",
    city: "Damascus",
    hours_ago: 21,
    sources: [
      { name: "SANA Monitor", source_type: "news", publisher: "SANA", reliability_score: 55, raw_text: "Air defenses shoot down missiles targeting Damascus" },
      { name: "Analyst Confirmation", source_type: "manual", reliability_score: 88, raw_text: "Debris pattern consistent with interception, not ground strike" },
      { name: "Thermal Scan S2", source_type: "satellite", reliability_score: 80, raw_text: "Brief thermal bloom over Damascus, dissipated quickly" },
    ],
  },
  // Syria - Deir ez-Zor
  {
    title: "[DEMO] Strike on military outpost, Deir ez-Zor",
    summary: "Explosion at a military outpost in the Deir ez-Zor region. Multiple sources confirm strike.",
    event_type: "explosion",
    severity: 4,
    confidence_score: 79,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 35.3352,
    longitude: 40.1407,
    location_radius_km: 3,
    country: "Syria",
    region: "Deir ez-Zor Governorate",
    city: "Deir ez-Zor",
    hours_ago: 16,
    sources: [
      { name: "MEE Correspondent", source_type: "news", publisher: "Middle East Eye", reliability_score: 72, raw_text: "Strike on outpost near Deir ez-Zor city" },
      { name: "OSINT Analyst", source_type: "manual", reliability_score: 82, raw_text: "Geo-located via landmarks in video, confirmed location" },
    ],
  },
  // Syria - Latakia
  {
    title: "[DEMO] Naval base activity, Latakia port area",
    summary: "Increased vessel movement at Latakia naval facility. Defensive positioning observed.",
    event_type: "troop_movement",
    severity: 2,
    confidence_score: 65,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 35.5317,
    longitude: 35.7917,
    country: "Syria",
    region: "Latakia Governorate",
    city: "Latakia",
    hours_ago: 48,
    sources: [
      { name: "Maritime Intel", source_type: "satellite", reliability_score: 78, raw_text: "Three additional vessels berthed at naval facility" },
    ],
  },
  // Iraq - Baghdad
  {
    title: "[DEMO] Rocket attack on Green Zone, Baghdad",
    summary: "At least two Katyusha rockets fired toward the International Zone in Baghdad.",
    event_type: "missile",
    severity: 4,
    confidence_score: 91,
    verification_status: "verified",
    geolocation_precision: "exact",
    latitude: 33.3152,
    longitude: 44.3661,
    country: "Iraq",
    region: "Baghdad Governorate",
    city: "Baghdad",
    hours_ago: 4,
    sources: [
      { name: "Iraqi Security Media Cell", source_type: "api", reliability_score: 85, raw_text: "Two Katyusha rockets fell in the Green Zone perimeter" },
      { name: "Reuters Baghdad", source_type: "news", publisher: "Reuters", reliability_score: 90, raw_text: "Rocket attack on Green Zone, no casualties reported" },
      { name: "US Embassy Feed", source_type: "manual", reliability_score: 92, raw_text: "Indirect fire incident, perimeter secured" },
    ],
  },
  {
    title: "[DEMO] Drone swarm launched from Baghdad belt",
    summary: "A cluster of explosive drones launched from the Baghdad belt toward coalition positions.",
    event_type: "drone",
    severity: 4,
    confidence_score: 74,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 33.2500,
    longitude: 44.2000,
    location_radius_km: 15,
    country: "Iraq",
    region: "Baghdad Governorate",
    hours_ago: 11,
    sources: [
      { name: "CENTCOM Statement", source_type: "manual", reliability_score: 90, raw_text: "Multiple UAS threats detected and engaged" },
      { name: "Social Media Cluster", source_type: "social", reliability_score: 35, raw_text: "Drones spotted heading toward coalition base" },
    ],
  },
  // Iraq - Basra
  {
    title: "[DEMO] Explosion at oil infrastructure near Basra",
    summary: "Large explosion at a pipeline junction south of Basra. Fire visible from 20km away.",
    event_type: "fire",
    severity: 3,
    confidence_score: 87,
    verification_status: "verified",
    geolocation_precision: "exact",
    latitude: 30.5085,
    longitude: 47.7835,
    country: "Iraq",
    region: "Basra Governorate",
    city: "Basra",
    hours_ago: 28,
    sources: [
      { name: "Energy Infrastructure Watch", source_type: "news", publisher: "Platts", reliability_score: 85, raw_text: "Pipeline explosion confirmed at Zubair junction" },
      { name: "Hotspot Sensor H3", source_type: "satellite", reliability_score: 88, raw_text: "Large thermal anomaly, consistent with oil fire" },
      { name: "Basra Ops", source_type: "manual", reliability_score: 80, raw_text: "Confirmed sabotage of pipeline segment" },
    ],
  },
  // Iraq - Erbil
  {
    title: "[DEMO] Ballistic missile strike, Erbil airport vicinity",
    summary: "A ballistic missile impacted near Erbil International Airport. No aircraft damage reported.",
    event_type: "missile",
    severity: 5,
    confidence_score: 95,
    verification_status: "verified",
    geolocation_precision: "exact",
    latitude: 36.2375,
    longitude: 43.9630,
    country: "Iraq",
    region: "Kurdistan Region",
    city: "Erbil",
    hours_ago: 6,
    sources: [
      { name: "Kurdistan 24", source_type: "news", publisher: "Kurdistan 24", reliability_score: 82, raw_text: "Missile strike near Erbil airport confirmed" },
      { name: "KRG Security Council", source_type: "manual", reliability_score: 95, raw_text: "Ballistic missile impact 3km from airport perimeter" },
      { name: "Impact Imagery", source_type: "satellite", reliability_score: 90, raw_text: "Crater and blast radius consistent with medium ballistic warhead" },
    ],
  },
  // Lebanon - Beirut
  {
    title: "[DEMO] Airstrike in Beirut southern suburbs (Dahiyeh)",
    summary: "Reported airstrike in the Dahiyeh district, southern Beirut. Structural damage to residential buildings.",
    event_type: "airstrike",
    severity: 5,
    confidence_score: 89,
    verification_status: "verified",
    geolocation_precision: "exact",
    latitude: 33.8538,
    longitude: 35.5018,
    country: "Lebanon",
    region: "Beirut Governorate",
    city: "Beirut",
    hours_ago: 12,
    sources: [
      { name: "L'Orient Today", source_type: "news", publisher: "L'Orient Today", reliability_score: 85, raw_text: "Strike on Dahiyeh confirmed, buildings collapsed" },
      { name: "Analyst GeoRef A1", source_type: "manual", reliability_score: 90, raw_text: "Impact geo-referenced to specific block, crater confirmed" },
      { name: "Thermal Scan B3", source_type: "satellite", reliability_score: 84, raw_text: "Post-strike thermal: fire detected, high intensity" },
    ],
  },
  {
    title: "[DEMO] Anti-tank missile fired across Lebanese border",
    summary: "AT missile fired from south Lebanon targeting Israeli border post. Cross-border exchange follows.",
    event_type: "missile",
    severity: 3,
    confidence_score: 77,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 33.2705,
    longitude: 35.2031,
    location_radius_km: 5,
    country: "Lebanon",
    region: "South Governorate",
    city: "Tyre",
    hours_ago: 24,
    sources: [
      { name: "IDF Spokesperson", source_type: "manual", reliability_score: 80, raw_text: "Anti-tank missile fired from Lebanese territory" },
      { name: "Al Manar Monitor", source_type: "news", publisher: "Al Manar", reliability_score: 50, raw_text: "Resistance fires on enemy post" },
    ],
  },
  // Lebanon - Sidon
  {
    title: "[DEMO] Infrastructure strike, Sidon power station",
    summary: "Power infrastructure hit near Sidon, causing widespread blackouts across South Lebanon.",
    event_type: "infrastructure",
    severity: 3,
    confidence_score: 84,
    verification_status: "verified",
    geolocation_precision: "exact",
    latitude: 33.5597,
    longitude: 35.3711,
    country: "Lebanon",
    region: "South Governorate",
    city: "Sidon",
    hours_ago: 38,
    sources: [
      { name: "EDL Report", source_type: "api", reliability_score: 90, raw_text: "Electricite du Liban reports major grid damage near Sidon" },
      { name: "Local Journalist", source_type: "news", reliability_score: 72, raw_text: "Power lines destroyed in strike on substation" },
    ],
  },
  // Yemen - Sanaa
  {
    title: "[DEMO] Airstrike on Sanaa military base",
    summary: "Coalition airstrike on a military storage facility at the edge of Sanaa. Large secondary explosions.",
    event_type: "airstrike",
    severity: 4,
    confidence_score: 88,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 15.3694,
    longitude: 44.1910,
    location_radius_km: 5,
    country: "Yemen",
    region: "Sanaa Governorate",
    city: "Sanaa",
    hours_ago: 19,
    sources: [
      { name: "Yemen Monitor", source_type: "news", publisher: "Yemen Monitor", reliability_score: 75, raw_text: "Heavy airstrikes on military depot near Sanaa" },
      { name: "OC Media", source_type: "news", publisher: "OC Media", reliability_score: 78, raw_text: "Multiple secondary blasts reported after initial strike" },
      { name: "Satellite Pass", source_type: "satellite", reliability_score: 83, raw_text: "Smoke plume visible in post-strike imagery" },
    ],
  },
  // Yemen - Hodeidah
  {
    title: "[DEMO] Port infrastructure hit, Hodeidah",
    summary: "Crane and loading facility at Hodeidah port struck. Humanitarian access concern raised by UN.",
    event_type: "infrastructure",
    severity: 4,
    confidence_score: 92,
    verification_status: "verified",
    geolocation_precision: "exact",
    latitude: 14.7980,
    longitude: 42.9511,
    country: "Yemen",
    region: "Hodeidah Governorate",
    city: "Hodeidah",
    hours_ago: 33,
    sources: [
      { name: "UN OCHA Yemen", source_type: "api", reliability_score: 95, raw_text: "Port crane destroyed, access road damaged" },
      { name: "Reuters Yemen", source_type: "news", publisher: "Reuters", reliability_score: 90, raw_text: "Strike on Hodeidah port halts aid shipments" },
      { name: "Vessel Tracking", source_type: "satellite", reliability_score: 88, raw_text: "Ships diverting from Hodeidah following port strike" },
    ],
  },
  // Yemen - missile toward Red Sea
  {
    title: "[DEMO] Anti-ship missile fired toward Red Sea shipping lane",
    summary: "Ballistic missile fired from Houthi-controlled Yemen toward commercial shipping in Red Sea corridor.",
    event_type: "missile",
    severity: 4,
    confidence_score: 86,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 15.0000,
    longitude: 43.5000,
    location_radius_km: 30,
    country: "Yemen",
    region: "Hodeidah Governorate",
    hours_ago: 7,
    sources: [
      { name: "UKMTO Alert", source_type: "api", reliability_score: 92, raw_text: "UKMTO vessel advisory: missile launch detected from Yemen" },
      { name: "MarineTraffic", source_type: "api", reliability_score: 85, raw_text: "Ships reporting evasive action in corridor" },
    ],
  },
  // Gaza
  {
    title: "[DEMO] Airstrike on northern Gaza City",
    summary: "Multiple strikes reported in Shati refugee camp and surrounding areas of northern Gaza.",
    event_type: "airstrike",
    severity: 5,
    confidence_score: 93,
    verification_status: "verified",
    geolocation_precision: "exact",
    latitude: 31.5354,
    longitude: 34.4588,
    country: "Gaza",
    region: "North Gaza",
    city: "Gaza City",
    hours_ago: 1,
    sources: [
      { name: "Al Jazeera Gaza", source_type: "news", publisher: "Al Jazeera", reliability_score: 82, raw_text: "Strikes on camp area confirmed by medical sources" },
      { name: "IDF Statement", source_type: "manual", reliability_score: 85, raw_text: "Targeted infrastructure used for military purposes" },
      { name: "OCHA oPt", source_type: "api", reliability_score: 95, raw_text: "Residential area damaged, casualties being assessed" },
      { name: "Satellite PlanetScope", source_type: "satellite", reliability_score: 88, raw_text: "Significant structural damage visible" },
    ],
  },
  {
    title: "[DEMO] Rocket barrage from Gaza toward Israel",
    summary: "Large rocket salvo launched from central Gaza. Iron Dome activated over several Israeli cities.",
    event_type: "missile",
    severity: 4,
    confidence_score: 91,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 31.4500,
    longitude: 34.3800,
    location_radius_km: 10,
    country: "Gaza",
    region: "Gaza Strip",
    hours_ago: 3,
    sources: [
      { name: "IDF Spokesperson", source_type: "manual", reliability_score: 90, raw_text: "Over 30 rockets fired from Gaza, most intercepted" },
      { name: "Haaretz", source_type: "news", publisher: "Haaretz", reliability_score: 88, raw_text: "Sirens across southern Israel, Iron Dome intercepts" },
    ],
  },
  {
    title: "[DEMO] Ground assault reported in Rafah",
    summary: "Armored forces moving into eastern Rafah. Heavy exchanges with armed groups.",
    event_type: "troop_movement",
    severity: 5,
    confidence_score: 80,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 31.2968,
    longitude: 34.2516,
    location_radius_km: 4,
    country: "Gaza",
    region: "Rafah",
    city: "Rafah",
    hours_ago: 15,
    sources: [
      { name: "AP Reporter Gaza", source_type: "news", publisher: "AP", reliability_score: 88, raw_text: "Armored columns seen entering east Rafah" },
      { name: "Social Geo-tag", source_type: "social", reliability_score: 40, raw_text: "Tanks and APCs rolling past Rafah crossing" },
    ],
  },
  // Additional Iran events
  {
    title: "[DEMO] Missile launch detected from western Iran",
    summary: "Surveillance assets detect ballistic missile launch from Kermanshah Province heading westward.",
    event_type: "missile",
    severity: 5,
    confidence_score: 88,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 34.3277,
    longitude: 47.0780,
    location_radius_km: 20,
    country: "Iran",
    region: "Kermanshah Province",
    city: "Kermanshah",
    hours_ago: 10,
    sources: [
      { name: "Missile Defense Tracking", source_type: "api", reliability_score: 92, raw_text: "MRBM launch detected, trajectory westward" },
      { name: "CENTCOM Intel", source_type: "manual", reliability_score: 90, raw_text: "Ballistic missile with range 500km+ launched from Iran" },
    ],
  },
  {
    title: "[DEMO] Drone factory fire, Karaj",
    summary: "Fire at a suspected drone production facility near Karaj, northwest of Tehran.",
    event_type: "fire",
    severity: 3,
    confidence_score: 68,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 35.8323,
    longitude: 50.9994,
    location_radius_km: 5,
    country: "Iran",
    region: "Alborz Province",
    city: "Karaj",
    hours_ago: 52,
    sources: [
      { name: "Thermal Hotspot K1", source_type: "satellite", reliability_score: 82, raw_text: "Intense thermal anomaly near industrial complex, Karaj" },
      { name: "Analyst Note", source_type: "manual", reliability_score: 75, raw_text: "Location matches previously identified drone assembly site" },
    ],
  },
  {
    title: "[DEMO] Anti-aircraft fire over Mashhad",
    summary: "AAA tracers and interceptor fire observed over Mashhad. Reports of unknown aircraft in area.",
    event_type: "alert",
    severity: 3,
    confidence_score: 58,
    verification_status: "partial",
    geolocation_precision: "area",
    latitude: 36.2972,
    longitude: 59.6067,
    location_radius_km: 20,
    country: "Iran",
    region: "Razavi Khorasan Province",
    city: "Mashhad",
    hours_ago: 27,
    sources: [
      { name: "Photo Evidence M1", source_type: "social", reliability_score: 48, raw_text: "Tracer rounds visible in night sky over Mashhad" },
      { name: "Local Radio", source_type: "news", reliability_score: 55, raw_text: "Air defense exercise announced after tracers spotted" },
    ],
  },
  // West Bank
  {
    title: "[DEMO] Airstrike on armed cell, Jenin",
    summary: "Israeli drone strike targeting armed fighters in Jenin refugee camp.",
    event_type: "drone",
    severity: 4,
    confidence_score: 85,
    verification_status: "verified",
    geolocation_precision: "exact",
    latitude: 32.4672,
    longitude: 35.3021,
    country: "West Bank",
    region: "Jenin",
    city: "Jenin",
    hours_ago: 7,
    sources: [
      { name: "IDF Blog", source_type: "manual", reliability_score: 82, raw_text: "Drone strike on armed cell in Jenin camp" },
      { name: "WAFA", source_type: "news", publisher: "WAFA", reliability_score: 72, raw_text: "Strike in Jenin camp, casualties reported" },
    ],
  },
  // More Iran
  {
    title: "[DEMO] Explosion in Qom, possible pipeline incident",
    summary: "Explosion and fire near a gas pipeline junction south of Qom. Investigation underway.",
    event_type: "explosion",
    severity: 2,
    confidence_score: 55,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 34.6416,
    longitude: 50.8746,
    location_radius_km: 6,
    country: "Iran",
    region: "Qom Province",
    city: "Qom",
    hours_ago: 41,
    sources: [
      { name: "Energy Infrawatch", source_type: "news", reliability_score: 65, raw_text: "Gas pipeline explosion near Qom, fire brigade responding" },
    ],
  },
  {
    title: "[DEMO] Drone intercepted over Kharg Island",
    summary: "Iranian air defenses intercept drone approaching Kharg Island oil terminal in Persian Gulf.",
    event_type: "drone",
    severity: 4,
    confidence_score: 78,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 29.2364,
    longitude: 50.3228,
    location_radius_km: 10,
    country: "Iran",
    region: "Bushehr Province",
    city: "Kharg Island",
    hours_ago: 20,
    sources: [
      { name: "IRGC Navy", source_type: "manual", reliability_score: 70, raw_text: "Hostile drone approaching Kharg intercepted" },
      { name: "PetroWatch", source_type: "news", reliability_score: 72, raw_text: "Oil tanker loading briefly suspended at Kharg" },
    ],
  },
  // Iraq - Mosul
  {
    title: "[DEMO] IED detonation, Mosul outskirts",
    summary: "Improvised explosive device detonated on road north of Mosul. Vehicle destroyed.",
    event_type: "explosion",
    severity: 3,
    confidence_score: 80,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 36.3419,
    longitude: 43.1158,
    location_radius_km: 3,
    country: "Iraq",
    region: "Nineveh Governorate",
    city: "Mosul",
    hours_ago: 32,
    sources: [
      { name: "ISF Statement", source_type: "manual", reliability_score: 80, raw_text: "IED confirmed on northern Mosul road, military vehicle targeted" },
      { name: "Mosul Eye", source_type: "social", reliability_score: 65, raw_text: "Explosion on road to Tal Afar" },
    ],
  },
  // Additional synthetic events to reach 50+
  {
    title: "[DEMO] Airstrike on weapon storage, Syrian border area",
    summary: "Strike on a suspected weapons cache near the Syrian-Iraqi border.",
    event_type: "airstrike",
    severity: 3,
    confidence_score: 72,
    verification_status: "partial",
    geolocation_precision: "area",
    latitude: 34.5000,
    longitude: 40.5000,
    location_radius_km: 15,
    country: "Syria",
    region: "Deir ez-Zor Governorate",
    hours_ago: 40,
    sources: [
      { name: "Syrian Observatory", source_type: "news", publisher: "SOHR", reliability_score: 70, raw_text: "Strikes on logistics route near border" },
    ],
  },
  {
    title: "[DEMO] Missile attack on US base, Al-Asad airbase Iraq",
    summary: "Ballistic missiles fired toward Al-Asad Air Base in Anbar Province. Interception attempted.",
    event_type: "missile",
    severity: 5,
    confidence_score: 93,
    verification_status: "verified",
    geolocation_precision: "exact",
    latitude: 33.7874,
    longitude: 42.4411,
    country: "Iraq",
    region: "Anbar Governorate",
    hours_ago: 15,
    sources: [
      { name: "CENTCOM", source_type: "manual", reliability_score: 93, raw_text: "Multiple ballistic missiles fired at Al-Asad AB, defensive systems engaged" },
      { name: "AP Iraq", source_type: "news", publisher: "AP", reliability_score: 90, raw_text: "Attack on US base in Anbar confirmed" },
    ],
  },
  {
    title: "[DEMO] Drone swarm intercept, northern Israel",
    summary: "Large drone swarm launched from Lebanon neutralized by Israeli air defense over northern Israel.",
    event_type: "drone",
    severity: 4,
    confidence_score: 90,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 33.0000,
    longitude: 35.5000,
    location_radius_km: 20,
    country: "Israel",
    region: "Northern District",
    hours_ago: 6,
    sources: [
      { name: "IDF Spokesperson", source_type: "manual", reliability_score: 90, raw_text: "35 drones launched from Lebanon, 33 intercepted" },
      { name: "Channel 12 Israel", source_type: "news", publisher: "Channel 12", reliability_score: 85, raw_text: "Iron Dome and David's Sling intercept drone swarm over Galilee" },
    ],
  },
  {
    title: "[DEMO] Explosion near IRGC compound, Hamadan",
    summary: "Explosion at or near an IRGC military compound in Hamadan Province. Cause unknown.",
    event_type: "explosion",
    severity: 3,
    confidence_score: 52,
    verification_status: "unverified",
    geolocation_precision: "area",
    latitude: 34.7992,
    longitude: 48.5146,
    location_radius_km: 15,
    country: "Iran",
    region: "Hamadan Province",
    city: "Hamadan",
    hours_ago: 60,
    sources: [
      { name: "Unverified X Post", source_type: "social", reliability_score: 20, raw_text: "Big explosion heard near army base in Hamadan area" },
      { name: "Regional Correspondent", source_type: "news", reliability_score: 50, raw_text: "Reports of explosion, no confirmation from authorities" },
    ],
  },
  {
    title: "[DEMO] Sea drone attack, Gulf of Oman",
    summary: "Suspected maritime drone attacked a commercial tanker in the Gulf of Oman.",
    event_type: "drone",
    severity: 4,
    confidence_score: 82,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 23.5000,
    longitude: 59.0000,
    location_radius_km: 30,
    country: "International Waters",
    region: "Gulf of Oman",
    hours_ago: 18,
    sources: [
      { name: "UKMTO", source_type: "api", reliability_score: 92, raw_text: "Tanker reports being struck by unknown drone, taking water" },
      { name: "Lloyd's Intelligence", source_type: "api", reliability_score: 90, raw_text: "MV [redacted] damaged by suspected surface drone" },
    ],
  },
  {
    title: "[DEMO] Thermal hotspot, eastern Syria",
    summary: "VIIRS satellite detects thermal anomaly consistent with vehicle or equipment fire in eastern Syria.",
    event_type: "fire",
    severity: 2,
    confidence_score: 55,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 34.8000,
    longitude: 40.9000,
    location_radius_km: 8,
    country: "Syria",
    region: "Deir ez-Zor Governorate",
    hours_ago: 25,
    sources: [
      { name: "NASA FIRMS", source_type: "satellite", reliability_score: 85, raw_text: "VIIRS hotspot detected, FRP 42MW, not typical agricultural burn" },
    ],
  },
  {
    title: "[DEMO] Missile test launch, south Iran",
    summary: "IRGC Aerospace Force conducts announced ballistic missile test exercise from Khuzestan.",
    event_type: "missile",
    severity: 3,
    confidence_score: 95,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 30.0000,
    longitude: 49.5000,
    location_radius_km: 25,
    country: "Iran",
    region: "Khuzestan Province",
    hours_ago: 96,
    sources: [
      { name: "IRGC Statement", source_type: "manual", reliability_score: 85, raw_text: "IRGC announces successful Fatah-2 missile test" },
      { name: "Tasnim News", source_type: "news", publisher: "Tasnim", reliability_score: 55, raw_text: "New generation missile tested, 1400km range claimed" },
    ],
  },
  {
    title: "[DEMO] Infrastructure damage, Homs electricity grid",
    summary: "Power lines and transmission towers destroyed in strike on Homs Province electricity infrastructure.",
    event_type: "infrastructure",
    severity: 3,
    confidence_score: 78,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 34.7324,
    longitude: 36.7137,
    country: "Syria",
    region: "Homs Governorate",
    city: "Homs",
    hours_ago: 44,
    sources: [
      { name: "Syrian Energy Ministry", source_type: "api", reliability_score: 70, raw_text: "Sabotage of transmission towers leaves 200,000 without power" },
      { name: "SOHR", source_type: "news", publisher: "SOHR", reliability_score: 70, raw_text: "Infrastructure attack on Homs grid confirmed" },
    ],
  },
  {
    title: "[DEMO] Drone strike on convoy, Abu Kamal",
    summary: "Strike on logistics convoy near Abu Kamal crossing on Syrian-Iraqi border.",
    event_type: "drone",
    severity: 3,
    confidence_score: 76,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 34.4504,
    longitude: 40.9185,
    country: "Syria",
    region: "Deir ez-Zor Governorate",
    city: "Abu Kamal",
    hours_ago: 22,
    sources: [
      { name: "Iraq Military Monitor", source_type: "news", reliability_score: 68, raw_text: "Strike on convoy near border crossing" },
      { name: "OSINT T1", source_type: "manual", reliability_score: 78, raw_text: "Drone strike confirmed, vehicles destroyed" },
    ],
  },
  {
    title: "[DEMO] Alert: unidentified aircraft, northern Iran border",
    summary: "Unknown aircraft entered Iranian airspace briefly near Azerbaijani border before returning.",
    event_type: "alert",
    severity: 2,
    confidence_score: 48,
    verification_status: "unverified",
    geolocation_precision: "area",
    latitude: 38.5000,
    longitude: 47.5000,
    location_radius_km: 30,
    country: "Iran",
    region: "East Azerbaijan Province",
    hours_ago: 50,
    sources: [
      { name: "Aviation Source", source_type: "social", reliability_score: 35, raw_text: "Unidentified craft near border, IRIAF scrambled" },
    ],
  },
  {
    title: "[DEMO] Suicide drone attack, Sinjar",
    summary: "Explosive drone detonated on vehicles near Sinjar. Yazidi community area affected.",
    event_type: "drone",
    severity: 3,
    confidence_score: 74,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 36.3167,
    longitude: 41.8333,
    country: "Iraq",
    region: "Nineveh Governorate",
    city: "Sinjar",
    hours_ago: 35,
    sources: [
      { name: "Rudaw", source_type: "news", publisher: "Rudaw", reliability_score: 78, raw_text: "Drone attack on vehicles in Sinjar area" },
      { name: "Local Security Source", source_type: "manual", reliability_score: 72, raw_text: "Shahid-type drone used in attack" },
    ],
  },
  {
    title: "[DEMO] Fire at fuel depot, Yemen Marib",
    summary: "Fire at fuel storage depot in Marib Province. Cause: shelling or technical failure unclear.",
    event_type: "fire",
    severity: 3,
    confidence_score: 65,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 15.4696,
    longitude: 45.3238,
    country: "Yemen",
    region: "Marib Governorate",
    city: "Marib",
    hours_ago: 43,
    sources: [
      { name: "NASA FIRMS M2", source_type: "satellite", reliability_score: 85, raw_text: "Large thermal signature in Marib, fuel fire characteristics" },
      { name: "Yemen Post", source_type: "news", reliability_score: 60, raw_text: "Fuel depot fire in Marib, conflicting reports on cause" },
    ],
  },
  {
    title: "[DEMO] Artillery exchange, South Lebanon frontier",
    summary: "Artillery rounds exchanged across Blue Line in South Lebanon. Limited civilian casualties.",
    event_type: "explosion",
    severity: 3,
    confidence_score: 83,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 33.1000,
    longitude: 35.4000,
    location_radius_km: 5,
    country: "Lebanon",
    region: "South Governorate",
    hours_ago: 13,
    sources: [
      { name: "UNIFIL Report", source_type: "manual", reliability_score: 92, raw_text: "Artillery exchange along Blue Line, both sides fired" },
      { name: "Al Mayadeen", source_type: "news", publisher: "Al Mayadeen", reliability_score: 60, raw_text: "Resistance response to enemy aggression" },
    ],
  },
  {
    title: "[DEMO] Drone attack on Israeli gas platform area",
    summary: "Drone launched toward Karish gas field in Mediterranean. Intercepted before reaching target.",
    event_type: "drone",
    severity: 4,
    confidence_score: 85,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 33.0833,
    longitude: 34.4167,
    location_radius_km: 15,
    country: "International Waters",
    region: "Eastern Mediterranean",
    hours_ago: 30,
    sources: [
      { name: "Energean Security", source_type: "api", reliability_score: 90, raw_text: "Drone threat detected and neutralized near platform" },
      { name: "Israeli Navy", source_type: "manual", reliability_score: 90, raw_text: "Naval forces intercepted armed UAV approaching gas platform" },
    ],
  },
  {
    title: "[DEMO] Ballistic missile barrage, Israel south",
    summary: "Salvo of ballistic missiles from Yemen impacts or intercepted over southern Israel.",
    event_type: "missile",
    severity: 5,
    confidence_score: 94,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 31.2530,
    longitude: 34.7915,
    location_radius_km: 20,
    country: "Israel",
    region: "Southern District",
    hours_ago: 2,
    sources: [
      { name: "IDF Spokesperson", source_type: "manual", reliability_score: 92, raw_text: "Ballistic missiles from Yemen, Arrow system activated" },
      { name: "Times of Israel", source_type: "news", publisher: "Times of Israel", reliability_score: 88, raw_text: "Sirens across southern Israel, impact near Beer Sheva" },
      { name: "Houthi Media", source_type: "news", reliability_score: 40, raw_text: "Hypersonic missile fired toward occupied territories" },
    ],
  },
  {
    title: "[DEMO] Arms cache discovered, eastern Lebanon",
    summary: "Lebanese Army discovers large weapons cache near the Syrian border. Missiles and drones recovered.",
    event_type: "alert",
    severity: 2,
    confidence_score: 79,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 33.5000,
    longitude: 36.1000,
    country: "Lebanon",
    region: "Bekaa Governorate",
    hours_ago: 58,
    sources: [
      { name: "LAF Statement", source_type: "manual", reliability_score: 85, raw_text: "Lebanese Army uncovers cache with anti-tank missiles and UAVs" },
      { name: "L'Orient Le Jour", source_type: "news", publisher: "L'Orient Le Jour", reliability_score: 82, raw_text: "Significant weapons find in Bekaa Valley" },
    ],
  },
  {
    title: "[DEMO] Airstrike near Palmyra, central Syria",
    summary: "Strike on suspected ammunition depot near ancient Palmyra site.",
    event_type: "airstrike",
    severity: 3,
    confidence_score: 71,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 34.5519,
    longitude: 38.2668,
    location_radius_km: 8,
    country: "Syria",
    region: "Homs Governorate",
    city: "Palmyra",
    hours_ago: 39,
    sources: [
      { name: "SOHR", source_type: "news", publisher: "SOHR", reliability_score: 70, raw_text: "Strikes near Tadmur (Palmyra) on arms storage" },
      { name: "Remote Sensing Analysis", source_type: "satellite", reliability_score: 80, raw_text: "Pre/post imagery shows structural change at site" },
    ],
  },
  {
    title: "[DEMO] Cyberattack on Iranian port management system",
    summary: "Bandar Abbas port management system disrupted by cyberattack. Operations partially suspended.",
    event_type: "infrastructure",
    severity: 3,
    confidence_score: 68,
    verification_status: "partial",
    geolocation_precision: "exact",
    latitude: 27.1832,
    longitude: 56.2785,
    country: "Iran",
    region: "Hormozgan Province",
    city: "Bandar Abbas",
    hours_ago: 76,
    sources: [
      { name: "Reuters Cyber", source_type: "news", publisher: "Reuters", reliability_score: 85, raw_text: "Iran port system knocked offline by suspected cyberattack" },
      { name: "Tech Monitor", source_type: "api", reliability_score: 72, raw_text: "Port management software shows indicators of compromise" },
    ],
  },
  {
    title: "[DEMO] Troop reinforcement, Iran-Iraq border",
    summary: "IRGC reinforces border positions along Khuzestan-Basra border segment.",
    event_type: "troop_movement",
    severity: 2,
    confidence_score: 60,
    verification_status: "partial",
    geolocation_precision: "area",
    latitude: 31.0000,
    longitude: 47.6000,
    location_radius_km: 25,
    country: "Iran",
    region: "Khuzestan Province",
    hours_ago: 82,
    sources: [
      { name: "Commercial Satellite W1", source_type: "satellite", reliability_score: 80, raw_text: "Vehicle concentration increase along border segment" },
    ],
  },
  {
    title: "[DEMO] Mortar attack on Golan Heights",
    summary: "Mortar shells land in Golan Heights area. No casualties. IDF returns fire.",
    event_type: "explosion",
    severity: 3,
    confidence_score: 86,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 33.1000,
    longitude: 35.7700,
    location_radius_km: 3,
    country: "Israel",
    region: "Golan Heights",
    hours_ago: 17,
    sources: [
      { name: "IDF Spokesperson", source_type: "manual", reliability_score: 90, raw_text: "Mortar fire from Syria into Golan, IDF artillery returned fire" },
      { name: "Times of Israel", source_type: "news", publisher: "Times of Israel", reliability_score: 88, raw_text: "Mortar attack on Golan Heights open area" },
    ],
  },
  {
    title: "[DEMO] Missile impact in Red Sea, near shipping lane",
    summary: "Ballistic missile impacted Red Sea approximately 15km from commercial shipping corridor.",
    event_type: "missile",
    severity: 3,
    confidence_score: 82,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 14.5000,
    longitude: 43.0000,
    location_radius_km: 25,
    country: "International Waters",
    region: "Red Sea",
    hours_ago: 9,
    sources: [
      { name: "UKMTO Advisory", source_type: "api", reliability_score: 92, raw_text: "Missile splashdown 15nm from shipping lane" },
      { name: "MarineTraffic", source_type: "api", reliability_score: 84, raw_text: "Ships rerouting around impact area" },
    ],
  },
  {
    title: "[DEMO] Strike on Syrian arms depot, T4 airbase",
    summary: "Large explosion at T4 (Tiyas) military airbase, central Syria. Secondary blasts indicate munitions storage hit.",
    event_type: "airstrike",
    severity: 4,
    confidence_score: 88,
    verification_status: "verified",
    geolocation_precision: "exact",
    latitude: 34.5256,
    longitude: 37.6213,
    country: "Syria",
    region: "Homs Governorate",
    city: "T4 Airbase",
    hours_ago: 26,
    sources: [
      { name: "SOHR", source_type: "news", publisher: "SOHR", reliability_score: 70, raw_text: "Massive explosion at T4 airbase, secondary blasts ongoing" },
      { name: "Satellite SAR", source_type: "satellite", reliability_score: 90, raw_text: "SAR imagery shows destroyed revetments and new craters" },
      { name: "Analyst D2", source_type: "manual", reliability_score: 86, raw_text: "Confirmed: Israeli strike on Iranian-linked assets at T4" },
    ],
  },
  {
    title: "[DEMO] Drone base identified, Chabahar",
    summary: "Satellite imagery identifies new drone launch infrastructure near Chabahar, southeastern Iran.",
    event_type: "alert",
    severity: 2,
    confidence_score: 70,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 25.2919,
    longitude: 60.6412,
    location_radius_km: 10,
    country: "Iran",
    region: "Sistan and Baluchestan Province",
    city: "Chabahar",
    hours_ago: 100,
    sources: [
      { name: "Commercial SAR Pass", source_type: "satellite", reliability_score: 82, raw_text: "New structures consistent with drone launch pads near Chabahar" },
      { name: "Analyst Note V1", source_type: "manual", reliability_score: 80, raw_text: "Construction timeline: ~6 months, operational posture" },
    ],
  },
  {
    title: "[DEMO] IED attack on patrol, Kirkuk",
    summary: "IED detonated under military vehicle during patrol in rural Kirkuk. Casualties reported.",
    event_type: "explosion",
    severity: 4,
    confidence_score: 85,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 35.4681,
    longitude: 44.3922,
    country: "Iraq",
    region: "Kirkuk Governorate",
    city: "Kirkuk",
    hours_ago: 29,
    sources: [
      { name: "ISF Statement", source_type: "manual", reliability_score: 80, raw_text: "IED detonation on patrol vehicle south of Kirkuk" },
      { name: "Kurdistan24", source_type: "news", publisher: "Kurdistan24", reliability_score: 78, raw_text: "Soldiers wounded in Kirkuk IED blast" },
    ],
  },
  {
    title: "[DEMO] Missile barrage toward Haifa",
    summary: "Multiple rockets and missiles fired toward Haifa Bay area from Lebanese territory.",
    event_type: "missile",
    severity: 5,
    confidence_score: 91,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 32.7940,
    longitude: 34.9896,
    location_radius_km: 10,
    country: "Israel",
    region: "Haifa District",
    city: "Haifa",
    hours_ago: 4,
    sources: [
      { name: "IDF Statement", source_type: "manual", reliability_score: 92, raw_text: "Rocket barrage from Lebanon toward Haifa area, Iron Dome deployed" },
      { name: "Walla News", source_type: "news", publisher: "Walla", reliability_score: 85, raw_text: "Direct hit on industrial zone north Haifa" },
      { name: "Thermal Scan H1", source_type: "satellite", reliability_score: 80, raw_text: "Post-impact fire detected at industrial facility" },
    ],
  },
  {
    title: "[DEMO] Explosion near Houthi HQ, Sanaa",
    summary: "Large explosion near suspected Houthi command facilities in northern Sanaa.",
    event_type: "airstrike",
    severity: 5,
    confidence_score: 87,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 15.4000,
    longitude: 44.2100,
    location_radius_km: 3,
    country: "Yemen",
    region: "Sanaa Governorate",
    city: "Sanaa",
    hours_ago: 8,
    sources: [
      { name: "CENTCOM", source_type: "manual", reliability_score: 92, raw_text: "US strikes on Houthi command infrastructure in Sanaa" },
      { name: "Al Arabiya", source_type: "news", publisher: "Al Arabiya", reliability_score: 78, raw_text: "Massive strikes on Houthi facilities, smoke over Sanaa" },
    ],
  },
  {
    title: "[DEMO] Satellite hotspot cluster, northern Gaza",
    summary: "FIRMS satellite data shows multiple thermal clusters consistent with intense ground combat in northern Gaza.",
    event_type: "fire",
    severity: 4,
    confidence_score: 88,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 31.5200,
    longitude: 34.4700,
    location_radius_km: 5,
    country: "Gaza",
    region: "North Gaza",
    city: "Gaza City",
    hours_ago: 1,
    sources: [
      { name: "NASA FIRMS G1", source_type: "satellite", reliability_score: 88, raw_text: "12 distinct thermal anomalies clustered in northern Gaza, high intensity" },
    ],
  },
  {
    title: "[DEMO] Rocket salvo, Ashkelon",
    summary: "Rockets from Gaza impact Ashkelon city area. Iron Dome intercepts majority.",
    event_type: "missile",
    severity: 4,
    confidence_score: 90,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 31.6688,
    longitude: 34.5742,
    country: "Israel",
    region: "Southern District",
    city: "Ashkelon",
    hours_ago: 3,
    sources: [
      { name: "IDF", source_type: "manual", reliability_score: 92, raw_text: "Rockets from Gaza toward Ashkelon, most intercepted, one direct hit" },
      { name: "Kan News", source_type: "news", publisher: "Kan", reliability_score: 86, raw_text: "Direct hit on building in Ashkelon, emergency response" },
    ],
  },
  {
    title: "[DEMO] Strike on drone factory, Diyala Iraq",
    summary: "Coalition drone or airstrike on suspected armed drone production facility in Diyala Province.",
    event_type: "airstrike",
    severity: 3,
    confidence_score: 73,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 33.7489,
    longitude: 45.0736,
    location_radius_km: 5,
    country: "Iraq",
    region: "Diyala Governorate",
    hours_ago: 48,
    sources: [
      { name: "Iraqi Intel Source", source_type: "manual", reliability_score: 72, raw_text: "Facility used for UAS assembly destroyed" },
      { name: "Sotaliraq", source_type: "news", reliability_score: 60, raw_text: "Explosion at industrial site in Diyala" },
    ],
  },
  {
    title: "[DEMO] Naval mine discovered, Gulf of Aden",
    summary: "Commercial vessel reports naval mine contact in Gulf of Aden shipping lane. Mine detonated safely.",
    event_type: "alert",
    severity: 3,
    confidence_score: 78,
    verification_status: "partial",
    geolocation_precision: "area",
    latitude: 12.0000,
    longitude: 45.5000,
    location_radius_km: 30,
    country: "International Waters",
    region: "Gulf of Aden",
    hours_ago: 55,
    sources: [
      { name: "UKMTO Alert 2", source_type: "api", reliability_score: 90, raw_text: "Vessel reports mine contact in Gulf of Aden, minor damage" },
    ],
  },
  {
    title: "[DEMO] Ground offensive push, northern Gaza",
    summary: "Israeli ground forces advance into previously cleared northern Gaza neighborhoods.",
    event_type: "troop_movement",
    severity: 4,
    confidence_score: 85,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 31.5500,
    longitude: 34.4800,
    location_radius_km: 4,
    country: "Gaza",
    region: "North Gaza",
    hours_ago: 2,
    sources: [
      { name: "IDF Blog", source_type: "manual", reliability_score: 90, raw_text: "Ground forces operating in Beit Lahiya and Beit Hanoun" },
      { name: "Al Jazeera", source_type: "news", publisher: "Al Jazeera", reliability_score: 80, raw_text: "IDF forces enter neighborhoods in northern Gaza" },
    ],
  },
  {
    title: "[DEMO] Missile test, Red Sea area Houthi",
    summary: "Houthi forces announce successful test of new anti-ship missile over Red Sea.",
    event_type: "missile",
    severity: 3,
    confidence_score: 72,
    verification_status: "partial",
    geolocation_precision: "area",
    latitude: 15.6000,
    longitude: 42.5000,
    location_radius_km: 50,
    country: "Yemen",
    region: "Hudaydah Governorate",
    hours_ago: 78,
    sources: [
      { name: "Al Masirah TV", source_type: "news", publisher: "Al Masirah", reliability_score: 45, raw_text: "Houthi military announces test of Palestine-2 anti-ship missile" },
      { name: "UKMTO Warning", source_type: "api", reliability_score: 90, raw_text: "Missile activity reported in Red Sea northern sector" },
    ],
  },
  {
    title: "[DEMO] Explosion at Parchin military complex",
    summary: "Witnesses and satellite data suggest explosion at Parchin complex southeast of Tehran.",
    event_type: "explosion",
    severity: 4,
    confidence_score: 64,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 35.5278,
    longitude: 51.7741,
    location_radius_km: 6,
    country: "Iran",
    region: "Tehran Province",
    city: "Parchin",
    hours_ago: 66,
    sources: [
      { name: "Thermal Pass P1", source_type: "satellite", reliability_score: 82, raw_text: "Thermal event detected near Parchin perimeter" },
      { name: "Social Media P2", source_type: "social", reliability_score: 30, raw_text: "Explosion heard, smoke seen near military area east of Tehran" },
    ],
  },
  {
    title: "[DEMO] Mortar fire on UNIFIL position",
    summary: "Italian UNIFIL peacekeeping position in southern Lebanon struck by mortar rounds.",
    event_type: "explosion",
    severity: 3,
    confidence_score: 90,
    verification_status: "verified",
    geolocation_precision: "exact",
    latitude: 33.0600,
    longitude: 35.3700,
    country: "Lebanon",
    region: "South Governorate",
    hours_ago: 31,
    sources: [
      { name: "UNIFIL Press", source_type: "manual", reliability_score: 95, raw_text: "UNIFIL position receives indirect fire, no casualties" },
      { name: "Italian Defense Ministry", source_type: "manual", reliability_score: 92, raw_text: "Italian Leonte battalion position shelled, inquiry opened" },
    ],
  },
  {
    title: "[DEMO] Strike on Iranian-backed militia base, T3 pumping station",
    summary: "Strike on militia staging area at T3 oil pumping station near Syrian-Jordanian-Iraqi border tri-point.",
    event_type: "airstrike",
    severity: 3,
    confidence_score: 77,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 33.6330,
    longitude: 38.5670,
    country: "Syria",
    region: "Homs Governorate",
    hours_ago: 54,
    sources: [
      { name: "SOHR T3", source_type: "news", publisher: "SOHR", reliability_score: 70, raw_text: "Strike reported at T3 pumping station" },
      { name: "Regional Analyst", source_type: "manual", reliability_score: 78, raw_text: "Militia logistics node at T3 targeted" },
    ],
  },
  {
    title: "[DEMO] Explosion near Soleimani memorial site, Kerman",
    summary: "Improvised explosive device detonated near memorial site in Kerman Province.",
    event_type: "explosion",
    severity: 3,
    confidence_score: 91,
    verification_status: "verified",
    geolocation_precision: "exact",
    latitude: 30.2839,
    longitude: 57.0834,
    country: "Iran",
    region: "Kerman Province",
    city: "Kerman",
    hours_ago: 120,
    sources: [
      { name: "IRNA", source_type: "news", publisher: "IRNA", reliability_score: 60, raw_text: "Explosion near ceremony in Kerman, casualties reported" },
      { name: "Reuters Iran", source_type: "news", publisher: "Reuters", reliability_score: 90, raw_text: "Deadly blast at memorial gathering in Kerman" },
      { name: "Iran Law Enforcement", source_type: "manual", reliability_score: 85, raw_text: "IED attack confirmed, investigation underway" },
    ],
  },
  {
    title: "[DEMO] Drone attack foiled, Dubai port shipping",
    summary: "Authorities report intercepted drone threat near Jebel Ali port, Dubai. No damage.",
    event_type: "drone",
    severity: 3,
    confidence_score: 60,
    verification_status: "partial",
    geolocation_precision: "area",
    latitude: 25.0000,
    longitude: 55.0000,
    location_radius_km: 20,
    country: "UAE",
    region: "Dubai Emirate",
    city: "Dubai",
    hours_ago: 88,
    sources: [
      { name: "UAE NCEMA", source_type: "manual", reliability_score: 85, raw_text: "Drone threat near port neutralized, safety maintained" },
    ],
  },
  {
    title: "[DEMO] Mine strike, Gulf of Oman tanker",
    summary: "Oil tanker reports mine or limpet device attached to hull in Gulf of Oman.",
    event_type: "explosion",
    severity: 4,
    confidence_score: 80,
    verification_status: "partial",
    geolocation_precision: "approximate",
    latitude: 24.5000,
    longitude: 58.5000,
    location_radius_km: 20,
    country: "International Waters",
    region: "Gulf of Oman",
    hours_ago: 44,
    sources: [
      { name: "UKMTO Gulf", source_type: "api", reliability_score: 90, raw_text: "Tanker reports explosion and flooding, suspected mine" },
      { name: "Lloyd's List", source_type: "api", reliability_score: 88, raw_text: "MV damaged near Muscat approaches" },
    ],
  },
  {
    title: "[DEMO] IRGC speedboat swarm, Strait of Hormuz",
    summary: "Iranian speedboats in swarm formation harass commercial tankers in Strait of Hormuz transit.",
    event_type: "troop_movement",
    severity: 3,
    confidence_score: 82,
    verification_status: "verified",
    geolocation_precision: "approximate",
    latitude: 26.5958,
    longitude: 56.2715,
    location_radius_km: 15,
    country: "International Waters",
    region: "Strait of Hormuz",
    hours_ago: 14,
    sources: [
      { name: "US Navy 5th Fleet", source_type: "manual", reliability_score: 92, raw_text: "IRGCN vessels conducted unsafe maneuvers around commercial shipping" },
      { name: "MarineTraffic API", source_type: "api", reliability_score: 85, raw_text: "Tanker deviates from planned route, reports armed vessels" },
    ],
  },
];

async function seed() {
  const client = await pool.connect();
  try {
    // Check if already seeded
    const existing = await client.query("SELECT COUNT(*) FROM events");
    if (parseInt(existing.rows[0].count) > 0) {
      console.log(
        `Database already has ${existing.rows[0].count} events. Skipping seed.`
      );
      return;
    }

    console.log(`Seeding ${seedEvents.length} demo events...`);

    for (const evt of seedEvents) {
      const occurredAt = new Date(
        Date.now() - evt.hours_ago * 60 * 60 * 1000
      ).toISOString();

      // Insert event
      const eventRes = await client.query(
        `INSERT INTO events (
          title, summary, description, event_type, severity, confidence_score,
          verification_status, geolocation_precision, latitude, longitude,
          location_radius_km, country, region, city,
          occurred_at, first_seen_at, last_updated_at
        ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$15,$15)
        RETURNING id`,
        [
          evt.title,
          evt.summary,
          evt.description ?? null,
          evt.event_type,
          evt.severity,
          evt.confidence_score,
          evt.verification_status,
          evt.geolocation_precision,
          evt.latitude,
          evt.longitude,
          evt.location_radius_km ?? null,
          evt.country,
          evt.region ?? null,
          evt.city ?? null,
          occurredAt,
        ]
      );

      const eventId = eventRes.rows[0].id;

      // Insert sources and link them
      for (const src of evt.sources) {
        const srcRes = await client.query(
          `INSERT INTO sources (name, source_type, url, publisher, reliability_score, raw_text)
           VALUES ($1,$2,$3,$4,$5,$6) RETURNING id`,
          [
            src.name,
            src.source_type,
            src.url ?? null,
            src.publisher ?? null,
            src.reliability_score,
            src.raw_text ?? null,
          ]
        );
        const srcId = srcRes.rows[0].id;
        await client.query(
          `INSERT INTO event_sources (event_id, source_id) VALUES ($1,$2)`,
          [eventId, srcId]
        );
      }
    }

    console.log("Seed completed successfully.");
  } catch (err) {
    console.error("Seed failed:", err);
    process.exit(1);
  } finally {
    client.release();
    await pool.end();
  }
}

seed();
